# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\work\code\pyqt5\ui\main.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(963, 727)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(571, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.txtRaw = QtWidgets.QTextEdit(self.tab)
        self.txtRaw.setObjectName("txtRaw")
        self.verticalLayout.addWidget(self.txtRaw)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(500, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnEncoding = QtWidgets.QPushButton(self.groupBox)
        self.btnEncoding.setObjectName("btnEncoding")
        self.horizontalLayout.addWidget(self.btnEncoding)
        self.btnDecoding = QtWidgets.QPushButton(self.groupBox)
        self.btnDecoding.setObjectName("btnDecoding")
        self.horizontalLayout.addWidget(self.btnDecoding)
        self.btnExchange = QtWidgets.QPushButton(self.groupBox)
        self.btnExchange.setObjectName("btnExchange")
        self.horizontalLayout.addWidget(self.btnExchange)
        self.btnClear = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnClear.sizePolicy().hasHeightForWidth())
        self.btnClear.setSizePolicy(sizePolicy)
        self.btnClear.setObjectName("btnClear")
        self.horizontalLayout.addWidget(self.btnClear)
        self.cboxCodecType = QtWidgets.QComboBox(self.groupBox)
        self.cboxCodecType.setObjectName("cboxCodecType")
        self.cboxCodecType.addItem("")
        self.horizontalLayout.addWidget(self.cboxCodecType)
        self.verticalLayout.addWidget(self.groupBox)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.txtResult = QtWidgets.QTextEdit(self.tab)
        self.txtResult.setObjectName("txtResult")
        self.verticalLayout.addWidget(self.txtResult)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.txtJson = QtWidgets.QTextEdit(self.tab_2)
        self.txtJson.setObjectName("txtJson")
        self.verticalLayout_2.addWidget(self.txtJson)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnJsonFormat = QtWidgets.QPushButton(self.groupBox_2)
        self.btnJsonFormat.setObjectName("btnJsonFormat")
        self.horizontalLayout_2.addWidget(self.btnJsonFormat)
        self.btnJsonCompress = QtWidgets.QPushButton(self.groupBox_2)
        self.btnJsonCompress.setObjectName("btnJsonCompress")
        self.horizontalLayout_2.addWidget(self.btnJsonCompress)
        self.btnJsonEscape = QtWidgets.QPushButton(self.groupBox_2)
        self.btnJsonEscape.setObjectName("btnJsonEscape")
        self.horizontalLayout_2.addWidget(self.btnJsonEscape)
        self.btnJsonDeescape = QtWidgets.QPushButton(self.groupBox_2)
        self.btnJsonDeescape.setObjectName("btnJsonDeescape")
        self.horizontalLayout_2.addWidget(self.btnJsonDeescape)
        self.btnJsonCopy = QtWidgets.QPushButton(self.groupBox_2)
        self.btnJsonCopy.setObjectName("btnJsonCopy")
        self.horizontalLayout_2.addWidget(self.btnJsonCopy)
        self.btnJsonClear = QtWidgets.QPushButton(self.groupBox_2)
        self.btnJsonClear.setObjectName("btnJsonClear")
        self.horizontalLayout_2.addWidget(self.btnJsonClear)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 963, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.btnClear.clicked.connect(self.txtResult.clear)
        self.btnClear.clicked.connect(self.txtRaw.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Raw Text:"))
        self.groupBox.setTitle(_translate("MainWindow", "Operation"))
        self.btnEncoding.setText(_translate("MainWindow", "Encoding"))
        self.btnDecoding.setText(_translate("MainWindow", "Decoding"))
        self.btnExchange.setText(_translate("MainWindow", "Exchange"))
        self.btnClear.setText(_translate("MainWindow", "Clear"))
        self.cboxCodecType.setItemText(0, _translate("MainWindow", "Base64"))
        self.label_2.setText(_translate("MainWindow", "Result Text:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Codec"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Operation"))
        self.btnJsonFormat.setText(_translate("MainWindow", "Format"))
        self.btnJsonCompress.setText(_translate("MainWindow", "Compress"))
        self.btnJsonEscape.setText(_translate("MainWindow", "Escape"))
        self.btnJsonDeescape.setText(_translate("MainWindow", "De-Escape"))
        self.btnJsonCopy.setText(_translate("MainWindow", "Copy"))
        self.btnJsonClear.setText(_translate("MainWindow", "Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Json"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

